variables:
  APP_NAME: "th2-verifier"
  MAJOR_VERSION: "0"
  MINOR_VERSION: "5"
  INSPECTION_ENABLED: 'true'
  TEST_ENABLED: 'false'
  ARTIFACTORY_PUBLISH: 'true'
  
include:
  - project: 'vivarium/th2/pipelines'
    ref: common
    file: '/.gitlab-ci-java.yml'
