variables:
  APP_NAME: "th2-verifier"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "2"
  MAINTENANCE_VERSION: '0'
  INSPECTION_ENABLED: 'false'
  DOCKER_PUBLISH_ENABLED: 'false'
  ARTIFACTORY_PUBLISH_ENABLED: 'true'
  TEST_ENABLED: 'false'

include:
  - project: 'vivarium/th2/pipelines'
    ref: th2-642
    file: '/.gitlab-ci-java.yml'
