include:
  - project: 'vivarium/th2/pipelines'
    ref: java-template
    file: '/.gitlab-ci-java-template.yml'

variables:
  APP_NAME: "th2-verifier"
  COMPONENT_TYPE: "core"
  INSPECTION_ENABLED: 'off'