include:
  - project: 'vivarium/th2/pipelines'
    ref: java-template
    file: '/.gitlab-ci-java-template.yml'

variables:
  APP_NAME: "th2-verifier"
  COMPONENT_TYPE: "core"
  MAJOR_VERSION: "0"
  MINOR_VERSION: "5"
  INSPECTION_ENABLED: 'true'
  TEST_ENABLED: 'false'
  ARTIFACTORY_PUBLISH: 'true'