image: 'openjdk:11.0.2'
stages:
  - build
build:
  image: docker
  stage: build
  script:
    - "export VERSION_MAINTENANCE=$(docker run --rm -v $(pwd):/git/ alpine/git:v2.26.2 rev-list --count VERSION-1.1..HEAD)"
    - " docker build -f ./ci/Dockerfile -t pipeline:${CI_PIPELINE_IID} --build-arg CI_JOB_TOKEN \
        --build-arg CI_PIPELINE_IID --build-arg VERSION_MAINTENANCE=${VERSION_MAINTENANCE} \
        --build-arg ARTIFACTORY_USER --build-arg ARTIFACTORY_PASS --build-arg ARTIFACTORY_REPO \
        --build-arg ARTIFACTORY_URL -- build-arg ARTIFACTORY_RESOLVE_REPO ."
    - "docker create -v $(pwd)/build:./build/libs -v $(pwd)/build:./build/distributions \
        -v $(pwd)/inspections:./inspections -v $(pwd)/imageName.txt:./imageName.txt"
    - "export IMAGE_NAME=$(cat ./imageName.txt)"
    - "docker tag pipeline:${CI_PIPELINE_IID} ${IMAGE_NAME}"
    - "docker login -u ${TH2_REGISTRY_USR} -p ${TH2_REGISTRY_PSW} ${TH2_REGISTRY_URL}"
    - "docker push ${IMAGE_NAME}"
  artifacts:
    paths:
      - 'build/*.jar'
      - 'build/*.tar'
      - 'build/*.zip'
      - 'inspection/results/*.xml'
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"

